# Generated by Django 4.2.10 on 2024-07-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='dateCompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
